model_list:
  - model_name: claude-opus-4-1
    litellm_params:
      model: claude-opus-4-1-20250805
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-sonnet-4
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: "os.environ/ANTHROPIC_API_KEY"
